name: Generate Image Index

on:
  push:
    branches: [ "main" ] # 当向main分支推送代码时触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # 检出仓库代码

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pathlib

      - name: Run index generator script
        run: python scripts/generate_index.py

      - name: Commit and push if index changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add images.json
          git diff --staged --quiet || (git commit -m "chore: auto-update images.json" && git push)
